package com.petbuddy.petapp.model;
// Generated 26-ene-2017 13:39:51 by Hibernate Tools 5.2.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name = "cliente", catalog = "petbuddy", uniqueConstraints = @UniqueConstraint(columnNames = "ID_PERSONA"))
public class Cliente implements java.io.Serializable {

	private Integer idCliente;
	private Persona persona;
	private String password;
	private Set<RelClienteMascota> relClienteMascotas = new HashSet<RelClienteMascota>(0);

	public Cliente() {
	}

	public Cliente(Persona persona) {
		this.persona = persona;
	}

	public Cliente(Persona persona, String password, Set<RelClienteMascota> relClienteMascotas) {
		this.persona = persona;
		this.password = password;
		this.relClienteMascotas = relClienteMascotas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_cliente", unique = true, nullable = false)
	public Integer getIdCliente() {
		return this.idCliente;
	}

	public void setIdCliente(Integer idCliente) {
		this.idCliente = idCliente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PERSONA", unique = true, nullable = false)
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@Column(name = "password", length = 500)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cliente")
	public Set<RelClienteMascota> getRelClienteMascotas() {
		return this.relClienteMascotas;
	}

	public void setRelClienteMascotas(Set<RelClienteMascota> relClienteMascotas) {
		this.relClienteMascotas = relClienteMascotas;
	}

}
