package com.petbuddy.petapp.model;
// Generated 26-ene-2017 13:39:51 by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Direccion generated by hbm2java
 */
@Entity
@Table(name = "direccion", catalog = "petbuddy")
public class Direccion implements java.io.Serializable {

	private Integer idDireccion;
	private Persona persona;
	private String nombreDireccion;
	private String distrito;
	private String provincia;
	private String departamento;
	private String ubigeo;
	private Double coordX;
	private Double coordY;

	public Direccion() {
	}

	public Direccion(Persona persona) {
		this.persona = persona;
	}

	public Direccion(Persona persona, String nombreDireccion, String distrito, String provincia, String departamento,
			String ubigeo, Double coordX, Double coordY) {
		this.persona = persona;
		this.nombreDireccion = nombreDireccion;
		this.distrito = distrito;
		this.provincia = provincia;
		this.departamento = departamento;
		this.ubigeo = ubigeo;
		this.coordX = coordX;
		this.coordY = coordY;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_DIRECCION", unique = true, nullable = false)
	public Integer getIdDireccion() {
		return this.idDireccion;
	}

	public void setIdDireccion(Integer idDireccion) {
		this.idDireccion = idDireccion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PERSONA", nullable = false)
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@Column(name = "NOMBRE_DIRECCION", length = 500)
	public String getNombreDireccion() {
		return this.nombreDireccion;
	}

	public void setNombreDireccion(String nombreDireccion) {
		this.nombreDireccion = nombreDireccion;
	}

	@Column(name = "DISTRITO", length = 50)
	public String getDistrito() {
		return this.distrito;
	}

	public void setDistrito(String distrito) {
		this.distrito = distrito;
	}

	@Column(name = "PROVINCIA", length = 50)
	public String getProvincia() {
		return this.provincia;
	}

	public void setProvincia(String provincia) {
		this.provincia = provincia;
	}

	@Column(name = "DEPARTAMENTO", length = 50)
	public String getDepartamento() {
		return this.departamento;
	}

	public void setDepartamento(String departamento) {
		this.departamento = departamento;
	}

	@Column(name = "UBIGEO", length = 6)
	public String getUbigeo() {
		return this.ubigeo;
	}

	public void setUbigeo(String ubigeo) {
		this.ubigeo = ubigeo;
	}

	@Column(name = "COORD_X", precision = 22, scale = 0)
	public Double getCoordX() {
		return this.coordX;
	}

	public void setCoordX(Double coordX) {
		this.coordX = coordX;
	}

	@Column(name = "COORD_Y", precision = 22, scale = 0)
	public Double getCoordY() {
		return this.coordY;
	}

	public void setCoordY(Double coordY) {
		this.coordY = coordY;
	}

}
