package com.petbuddy.petapp.model;
// Generated 26-ene-2017 13:39:51 by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ExpedienteMedico generated by hbm2java
 */
@Entity
@Table(name = "expediente_medico", catalog = "petbuddy")
public class ExpedienteMedico implements java.io.Serializable {

	private Integer idExpediente;
	private Mascota mascota;
	private String descripcion;
	private Date fecha;

	public ExpedienteMedico() {
	}

	public ExpedienteMedico(Mascota mascota) {
		this.mascota = mascota;
	}

	public ExpedienteMedico(Mascota mascota, String descripcion, Date fecha) {
		this.mascota = mascota;
		this.descripcion = descripcion;
		this.fecha = fecha;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_EXPEDIENTE", unique = true, nullable = false)
	public Integer getIdExpediente() {
		return this.idExpediente;
	}

	public void setIdExpediente(Integer idExpediente) {
		this.idExpediente = idExpediente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_MASCOTA", nullable = false)
	public Mascota getMascota() {
		return this.mascota;
	}

	public void setMascota(Mascota mascota) {
		this.mascota = mascota;
	}

	@Column(name = "DESCRIPCION", length = 500)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA", length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

}
