package com.petbuddy.petapp.model;
// Generated 26-ene-2017 13:39:51 by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Mascota generated by hbm2java
 */
@Entity
@Table(name = "mascota", catalog = "petbuddy")
public class Mascota implements java.io.Serializable {

	private Integer idMascota;
	private TipoMascota tipoMascota;
	private Character sexo;
	private Date birthday;
	private Set<ExpedienteMedico> expedienteMedicos = new HashSet<ExpedienteMedico>(0);
	private Set<RelClienteMascota> relClienteMascotas = new HashSet<RelClienteMascota>(0);

	public Mascota() {
	}

	public Mascota(TipoMascota tipoMascota) {
		this.tipoMascota = tipoMascota;
	}

	public Mascota(TipoMascota tipoMascota, Character sexo, Date birthday, Set<ExpedienteMedico> expedienteMedicos,
			Set<RelClienteMascota> relClienteMascotas) {
		this.tipoMascota = tipoMascota;
		this.sexo = sexo;
		this.birthday = birthday;
		this.expedienteMedicos = expedienteMedicos;
		this.relClienteMascotas = relClienteMascotas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_MASCOTA", unique = true, nullable = false)
	public Integer getIdMascota() {
		return this.idMascota;
	}

	public void setIdMascota(Integer idMascota) {
		this.idMascota = idMascota;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_TIPO_MASCOTA", nullable = false)
	public TipoMascota getTipoMascota() {
		return this.tipoMascota;
	}

	public void setTipoMascota(TipoMascota tipoMascota) {
		this.tipoMascota = tipoMascota;
	}

	@Column(name = "SEXO", length = 1)
	public Character getSexo() {
		return this.sexo;
	}

	public void setSexo(Character sexo) {
		this.sexo = sexo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "BIRTHDAY", length = 10)
	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mascota")
	public Set<ExpedienteMedico> getExpedienteMedicos() {
		return this.expedienteMedicos;
	}

	public void setExpedienteMedicos(Set<ExpedienteMedico> expedienteMedicos) {
		this.expedienteMedicos = expedienteMedicos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mascota")
	public Set<RelClienteMascota> getRelClienteMascotas() {
		return this.relClienteMascotas;
	}

	public void setRelClienteMascotas(Set<RelClienteMascota> relClienteMascotas) {
		this.relClienteMascotas = relClienteMascotas;
	}

}
