package com.petbuddy.petapp.model;
// Generated 26-ene-2017 13:39:51 by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * RelVeterinarioServicio generated by hbm2java
 */
@Entity
@Table(name = "rel_veterinario_servicio", catalog = "petbuddy", uniqueConstraints = @UniqueConstraint(columnNames = "ID_SERVICIO"))
public class RelVeterinarioServicio implements java.io.Serializable {

	private Integer idRelVeterinarioServicio;
	private Servicio servicio;
	private Veterinario veterinario;

	public RelVeterinarioServicio() {
	}

	public RelVeterinarioServicio(Servicio servicio, Veterinario veterinario) {
		this.servicio = servicio;
		this.veterinario = veterinario;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_REL_VETERINARIO_SERVICIO", unique = true, nullable = false)
	public Integer getIdRelVeterinarioServicio() {
		return this.idRelVeterinarioServicio;
	}

	public void setIdRelVeterinarioServicio(Integer idRelVeterinarioServicio) {
		this.idRelVeterinarioServicio = idRelVeterinarioServicio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_SERVICIO", unique = true, nullable = false)
	public Servicio getServicio() {
		return this.servicio;
	}

	public void setServicio(Servicio servicio) {
		this.servicio = servicio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_VETERINARIO", nullable = false)
	public Veterinario getVeterinario() {
		return this.veterinario;
	}

	public void setVeterinario(Veterinario veterinario) {
		this.veterinario = veterinario;
	}

}
