package com.petbuddy.petapp.model;
// Generated 26-ene-2017 13:39:51 by Hibernate Tools 5.2.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Servicio generated by hbm2java
 */
@Entity
@Table(name = "servicio", catalog = "petbuddy")
public class Servicio implements java.io.Serializable {

	private Integer idServicio;
	private int idTipoServicio;
	private String descripcion;
	private Double coordX;
	private Double coordY;
	private Set<RelVeterinarioServicio> relVeterinarioServicios = new HashSet<RelVeterinarioServicio>(0);

	public Servicio() {
	}

	public Servicio(int idTipoServicio) {
		this.idTipoServicio = idTipoServicio;
	}

	public Servicio(int idTipoServicio, String descripcion, Double coordX, Double coordY,
			Set<RelVeterinarioServicio> relVeterinarioServicios) {
		this.idTipoServicio = idTipoServicio;
		this.descripcion = descripcion;
		this.coordX = coordX;
		this.coordY = coordY;
		this.relVeterinarioServicios = relVeterinarioServicios;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_servicio", unique = true, nullable = false)
	public Integer getIdServicio() {
		return this.idServicio;
	}

	public void setIdServicio(Integer idServicio) {
		this.idServicio = idServicio;
	}

	@Column(name = "id_tipo_servicio", nullable = false)
	public int getIdTipoServicio() {
		return this.idTipoServicio;
	}

	public void setIdTipoServicio(int idTipoServicio) {
		this.idTipoServicio = idTipoServicio;
	}

	@Column(name = "descripcion", length = 200)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "coord_x", precision = 22, scale = 0)
	public Double getCoordX() {
		return this.coordX;
	}

	public void setCoordX(Double coordX) {
		this.coordX = coordX;
	}

	@Column(name = "coord_y", precision = 22, scale = 0)
	public Double getCoordY() {
		return this.coordY;
	}

	public void setCoordY(Double coordY) {
		this.coordY = coordY;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "servicio")
	public Set<RelVeterinarioServicio> getRelVeterinarioServicios() {
		return this.relVeterinarioServicios;
	}

	public void setRelVeterinarioServicios(Set<RelVeterinarioServicio> relVeterinarioServicios) {
		this.relVeterinarioServicios = relVeterinarioServicios;
	}

}
