package com.petbuddy.petapp.model;
// Generated 26-ene-2017 13:39:51 by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Transaccion generated by hbm2java
 */
@Entity
@Table(name = "transaccion", catalog = "petbuddy")
public class Transaccion implements java.io.Serializable {

	private Integer idTransaccion;
	private RelClienteMascota relClienteMascota;
	private int idServicio;

	public Transaccion() {
	}

	public Transaccion(RelClienteMascota relClienteMascota, int idServicio) {
		this.relClienteMascota = relClienteMascota;
		this.idServicio = idServicio;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_TRANSACCION", unique = true, nullable = false)
	public Integer getIdTransaccion() {
		return this.idTransaccion;
	}

	public void setIdTransaccion(Integer idTransaccion) {
		this.idTransaccion = idTransaccion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_REL_CLIENTE_MASCOTA", nullable = false)
	public RelClienteMascota getRelClienteMascota() {
		return this.relClienteMascota;
	}

	public void setRelClienteMascota(RelClienteMascota relClienteMascota) {
		this.relClienteMascota = relClienteMascota;
	}

	@Column(name = "ID_SERVICIO", nullable = false)
	public int getIdServicio() {
		return this.idServicio;
	}

	public void setIdServicio(int idServicio) {
		this.idServicio = idServicio;
	}

}
