package com.petbuddy.petapp.model;
// Generated 26-ene-2017 13:39:51 by Hibernate Tools 5.2.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Veterinario generated by hbm2java
 */
@Entity
@Table(name = "veterinario", catalog = "petbuddy")
public class Veterinario implements java.io.Serializable {

	private Integer idVeterinario;
	private Persona persona;
	private Boolean colegiado;
	private Set<RelVeterinarioServicio> relVeterinarioServicios = new HashSet<RelVeterinarioServicio>(0);

	public Veterinario() {
	}

	public Veterinario(Persona persona) {
		this.persona = persona;
	}

	public Veterinario(Persona persona, Boolean colegiado, Set<RelVeterinarioServicio> relVeterinarioServicios) {
		this.persona = persona;
		this.colegiado = colegiado;
		this.relVeterinarioServicios = relVeterinarioServicios;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_VETERINARIO", unique = true, nullable = false)
	public Integer getIdVeterinario() {
		return this.idVeterinario;
	}

	public void setIdVeterinario(Integer idVeterinario) {
		this.idVeterinario = idVeterinario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PERSONA", nullable = false)
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@Column(name = "COLEGIADO")
	public Boolean getColegiado() {
		return this.colegiado;
	}

	public void setColegiado(Boolean colegiado) {
		this.colegiado = colegiado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "veterinario")
	public Set<RelVeterinarioServicio> getRelVeterinarioServicios() {
		return this.relVeterinarioServicios;
	}

	public void setRelVeterinarioServicios(Set<RelVeterinarioServicio> relVeterinarioServicios) {
		this.relVeterinarioServicios = relVeterinarioServicios;
	}

}
