CREATE TABLE REL_CLIENTE_MASCOTA (
    ID_REL_CLIENTE_MASCOTA INTEGER NOT NULL PRIMARY KEY,
    ID_CLIENTE INTEGER NOT NULL REFERENCES CLIENTE(ID_CLIENTE),
    ID_MASCOTA INTEGER NOT NULL REFERENCES MASCOTA(ID_MASCOTA)
);